2018-07-10 19:15:54,545 ERROR: Exception on / [GET] [in /home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jsen/repos/microblog/app/main/routes.py", line 12, in index
    return render_template('index.html', title='Home')
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/jsen/repos/microblog/app/templates/index.html", line 22, in template
    {% block app_content %}
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/jinja2/environment.py", line 543, in _generate
    optimized=self.optimized)
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/jinja2/compiler.py", line 82, in generate
    generator.visit(node)
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/jinja2/visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/jinja2/compiler.py", line 691, in visit_Template
    self.fail('block %r defined twice' % block.name, block.lineno)
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/jinja2/compiler.py", line 309, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: block 'app_content' defined twice
2018-07-10 19:18:26,815 INFO: Microblog startup [in /home/jsen/repos/microblog/app/__init__.py:57]
2018-07-10 19:32:35,532 INFO: Microblog startup [in /home/jsen/repos/microblog/app/__init__.py:57]
2018-07-10 19:34:25,527 INFO: Microblog startup [in /home/jsen/repos/microblog/app/__init__.py:57]
2018-07-10 20:00:36,707 INFO: Microblog startup [in /home/jsen/repos/microblog/app/__init__.py:57]
2018-07-10 20:02:35,890 INFO: Microblog startup [in /home/jsen/repos/microblog/app/__init__.py:57]
2018-07-10 20:03:59,910 INFO: Microblog startup [in /home/jsen/repos/microblog/app/__init__.py:57]
2018-07-10 20:05:50,650 INFO: Microblog startup [in /home/jsen/repos/microblog/app/__init__.py:57]
2018-07-10 20:12:09,149 INFO: Microblog startup [in /home/jsen/repos/microblog/app/__init__.py:57]
2018-07-10 20:13:35,347 INFO: Microblog startup [in /home/jsen/repos/microblog/app/__init__.py:57]
2018-07-10 20:14:53,335 INFO: Microblog startup [in /home/jsen/repos/microblog/app/__init__.py:57]
2018-07-10 20:16:22,701 INFO: Microblog startup [in /home/jsen/repos/microblog/app/__init__.py:57]
2018-07-10 20:19:05,062 INFO: Microblog startup [in /home/jsen/repos/microblog/app/__init__.py:57]
2018-07-10 20:21:38,302 INFO: Microblog startup [in /home/jsen/repos/microblog/app/__init__.py:57]
2018-07-10 20:30:28,328 INFO: Microblog startup [in /home/jsen/repos/microblog/app/__init__.py:57]
2018-07-10 20:30:30,196 ERROR: Exception on /index [GET] [in /home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jsen/repos/microblog/app/main/routes.py", line 12, in index
    return render_template('index.html', title='Home')
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    context, ctx.app)
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/flask/templating.py", line 116, in _render
    rv = template.render(context)
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/jsen/repos/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/jsen/repos/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/home/jsen/anaconda3/envs/flask-site/lib/python3.6/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/base.html
