2018-07-09 23:00:06,680 INFO: Microblog startup [in /Users/jsen/Repos/microblog/app/__init__.py:57]
2018-07-09 23:00:14,368 ERROR: Exception on /index [GET] [in /Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jsen/Repos/microblog/app/main/routes.py", line 12, in index
    return render_template('index.html', title=_('Home'))
NameError: name '_' is not defined
2018-07-09 23:01:30,203 INFO: Microblog startup [in /Users/jsen/Repos/microblog/app/__init__.py:57]
2018-07-09 23:01:35,428 ERROR: Exception on /index [GET] [in /Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jsen/Repos/microblog/app/main/routes.py", line 12, in index
    return render_template('index.html', title=_('Home'))
NameError: name '_' is not defined
2018-07-09 23:04:50,859 INFO: Microblog startup [in /Users/jsen/Repos/microblog/app/__init__.py:57]
2018-07-09 23:04:56,151 ERROR: Exception on /index [GET] [in /Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jsen/Repos/microblog/app/main/routes.py", line 12, in index
    return render_template('index.html', title=_('Home'))
NameError: name '_' is not defined
2018-07-09 23:07:20,997 INFO: Microblog startup [in /Users/jsen/Repos/microblog/app/__init__.py:57]
2018-07-09 23:07:30,929 ERROR: Exception on /index [GET] [in /Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jsen/Repos/microblog/app/main/routes.py", line 12, in index
    return render_template('index.html', title=_('Home'))
NameError: name '_' is not defined
2018-07-09 23:08:22,205 INFO: Microblog startup [in /Users/jsen/Repos/microblog/app/__init__.py:57]
2018-07-09 23:08:25,269 ERROR: Exception on /index [GET] [in /Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jsen/Repos/microblog/app/main/routes.py", line 12, in index
    return render_template('index.html', title=_('Home'))
NameError: name '_' is not defined
2018-07-09 23:09:12,451 INFO: Microblog startup [in /Users/jsen/Repos/microblog/app/__init__.py:57]
2018-07-09 23:09:17,477 ERROR: Exception on /index [GET] [in /Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jsen/Repos/microblog/app/main/routes.py", line 12, in index
    return render_template('index.html', title=_('Home'))
NameError: name '_' is not defined
2018-07-09 23:09:41,789 INFO: Microblog startup [in /Users/jsen/Repos/microblog/app/__init__.py:57]
2018-07-09 23:09:45,351 ERROR: Exception on /index [GET] [in /Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jsen/anaconda3/envs/flaskapp/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jsen/Repos/microblog/app/main/routes.py", line 12, in index
    return render_template('index.html', title=_('Home'))
NameError: name '_' is not defined
2018-07-09 23:10:06,392 INFO: Microblog startup [in /Users/jsen/Repos/microblog/app/__init__.py:57]
